name: Website

on:
  push:
    branches: [master, main]
    paths:
      - website/**
      - .github/workflows/website.yml
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v5

      - name: Configure Pages
        uses: actions/configure-pages@v6
        with:
          token: ${{ secrets.PAGES_TOKEN || github.token }}
          enablement: ${{ secrets.PAGES_TOKEN != '' && 'true' || 'false' }}

      - name: Upload website
        uses: actions/upload-pages-artifact@v5
        with:
          path: website

      - name: Deploy website
        id: deployment
        uses: actions/deploy-pages@v4
